name: Deploy to Dev

on:
  push:
    branches: [ main ]

jobs:
  redeploy_everything:
    runs-on: ubuntu-latest
    name: Deploying everything to the staging cluster

    steps:
      - run: |
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/ssh_key
          chmod 700 ~/ssh_key

          mkdir -p /home/runner/.ssh
          echo "${{ secrets.KNOWN_HOSTS }}" > /home/runner/.ssh/known_hosts
          chmod 644 /home/runner/.ssh/known_hosts

          ssh -i ~/ssh_key -o StrictHostKeyChecking=no ubuntu@65.1.107.102 -t "
            cd Prisma-PostgreSQL-Nextjs-http-websocket &&
            git pull origin main &&
            export PATH=/home/ubuntu/.nvm/versions/node/v22.16.0/bin:\$PATH &&
            npm install -g pnpm &&
            pnpm install &&
            pnpm run build &&
            pm2 restart dev-nextjs-server --update-env &&
            pm2 restart dev-ht-server --update-env &&
            pm2 restart dev-ws-server --update-env
          "
